### ISSUE TITLE
getJob() is throwing an exception if no Job is in the queue

### ISSUE THREAD

**Issue by mzapletal** [xetorthio/jedisque#6]
If no job is in the queue `getJob()` throws an Exception. Is this the desired/expected behavior? I would rather have expected that an empty `List<Job>` is returned

``` java
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
    at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
    at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
    at redis.clients.jedis.Protocol.process(Protocol.java:132)
    at redis.clients.jedis.Protocol.read(Protocol.java:196)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288)
    at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:233)
    at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:239)
    at com.github.xetorthio.jedisque.Jedisque.getJob(Jedisque.java:38)
    at com.github.xetorthio.jedisque.JedisqueTest.showExceptionsOnGet(JedisqueTest.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:202)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:65)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at java.net.SocketInputStream.read(SocketInputStream.java:108)
    at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
    ... 36 more
```

**Comment by xetorthio** [comment]
This seems to be a bug.  The desired behavior is an empty List

**Comment by marcosnils** [comment]
I believe this is not a bug, the default implementation if disque is to block the connection when doing a `getjob` if no `timeout` is specified.  The reason why you're getting an exception is because `Jedisque` has a 2000ms default socket read timeout (which cannot be changed at this moment). 

If you don't want to your client to block for a job then you need to use the `getJob` command and specify a timeout lower than 2000 and you'll get a null response if no jobs are in the que. (disque returns null when there are no jobs in the que)

**Comment by marcosnils** [comment]
Regarding the default 2000ms timeout, I'll open a new issue so we can make that configurable.

**Comment by xetorthio** [comment]
I think it is a bug though.
Disque documentation states that a `GETJOB` timeout is optional. And if no timeout is specified then default is wait forever, which is something that we are not doing.
So what I am saying is that when `GETJOB` is called, if no timeout is specified, we need to set it internally to infinite.
